---
- name: Installation of nagios
  hosts: all
  user: root

  tasks:
     - name: nrpe command defination
       blockinfile:
         state: present
         insertafter: EOF
         dest: /etc/prometheus/prometheus.yml
         content: |
            - job_name: 'node_exporter_metrics'
              scrape_interval: 5s
              static_configs:
            - targets: ['3.110.120.438:9100']
