---
- name: Installation of nagios
  hosts: all
  user: root

  tasks: 
     - name: insert/update eth0 configuration stanza in /etc/network/interfaces
        (it might be better to copy files into /etc/network/interfaces.d/)
       blockinfile:
         path: /etc/prometheus/prometheus.yml
         block: |
          # iface eth0 inet static
              - targets: ['toob:9100']
              - targets: ['soob:9100']
      
      
- name: service module demo
  hosts: all
  become: true
  tasks:
    - name: prometheus restart
      ansible.builtin.service:
        name: prometheus
        state: restarted
        enabled: true
 
