---
- name: Installation of nagios
  hosts: all
  user: root

  tasks:
     - name: nrpe command defination
       blockinfile:
         state: present
         insertafter: EOF
         dest: /etc/prometheus/prometheus.yml
         content: |
            - job_name: 'node_exporter_metrics'
              scrape_interval: 5s
              static_configs:
            - targets: ['noob:9100','toob:9100,'soob:9100']


- name: service module demo
  hosts: all
  become: true
  tasks:
    - name: prometheus restart
      ansible.builtin.service:
        name: prometheus
        state: restarted
        enabled: true
 
