---
- name: Installation of nagios
  hosts: all
  user: root

  tasks:
     - name: nrpe command defination
       blockinfile:
         state: present
         insertafter: EOF
         dest: /etc/prometheus/prometheus.yml
         content: |
                  - targets: ['toob:9100']
                  - targets: ['soob:9100']

- name: service module demo
  hosts: all
  become: true
  tasks:
    - name: prometheus restart
      ansible.builtin.service:
        name: prometheus
        state: restarted
        enabled: true
 
